### ISSUE TITLE
Lampager\Contracts\Cursor should have empty() method

### ISSUE THREAD

**Issue by chitoku-k** [lampager/lampager#10]
In the previous implementation, array `$cursor` behaved as boolean as to whether it was empty or not.

https://github.com/lampager/lampager/blob/60017b647904d15ee245944231843a1a75d43dc2/src/Query/SelectOrUnionAll.php#L23-L31

## Issue

`$cursor` is always truthy which makes it fail to generate cursor query.

## Proposal

As `Cursor` object cannot pretend to be empty, the interface `Cursor` should also require this feature.

Any ideas? (for the method name or anything else)

**Comment by chitoku-k** [comment]
All we need is stipulate that every `$order->column()` exist in `$cursor`.

There should be a couple of options:

## Require pseudo-`empty()`
(as written above)

## Require `has` method that accepts multiple columns

```php
<?php
class ArrayCursor implements Cursor
{
    public function has(...$columns)
    {
        foreach ($columns as $column) {
            if (!isset($this->cursor[$column])) {
                return false;
            }
        }
        return true;
    }
}
```

**Comment by mpyw** [comment]
> Require `has` method that accepts multiple columns

I support this option

**Comment by chitoku-k** [comment]
I noticed that multiple-`has` does not solve this bug because the implementation would go like the following:

- If the `$cursor` does not have any of `$order->column()`, the `$cursor` would be treated as empty.
- If the `$cursor` has all of `$order->column()`, the query is made in a way of cursor-aware.

However, the proposal does not provide any ways to detect which case applies because `false` can mean
- not all of `$order->column()` exist
- none of `$order->column()` exist

**Comment by chitoku-k** [comment]
Since `Cursor` should be responsible for being compatible with `Order`s, I guess the new method can take `Order[]` as a parameter and then check compatibility.

**Comment by chitoku-k** [comment]
`Lampager\Contracts\Cursor` is going to have:

```php
<?php

interface Cursor
{
    /**
     * Return a value indicating whether the cursor is non-empty and has the specified columns.
     *
     * @return null|bool null if the cursor is empty; true if the cursor has all the columns; otherwise false.
     */
    public function has(...$columns);
}
```
