### ISSUE TITLE
Implement magic methods for Query components

### ISSUE THREAD

**Issue by mpyw** [lampager/lampager#2]
- `__get()` should return the corresponding member
- `__isset()` should return whether the corresponding member exists
- <del>`__set()` `__unset()` should always throw `\BadMethodCallException`</del>

**Comment by m3m0r7** [comment]
if magic method is used then some editors have problem that cannot suggest properties.

**Comment by chitoku-k** [comment]
We can have type annotations instead in order to have completions by editors.

**Comment by mpyw** [comment]
`Query` is mostly used as an internal feature. Heavy shorthand implementations are not necessary.
