### ISSUE TITLE
[Proposal] Lampager 1.0

### ISSUE THREAD

**Issue by mpyw** [lampager/lampager#31]
# Proposal

- Change type of `PaginationResult::$*Cursor` from `null|mixed` to `null|Cursor`.
- `AbstractProcessor::makeCursor()` to make `Cursor` instead of `int[]|string[]`.
  - `Cursor` implementation class will be the same as the first argument of `Paginator::paginate()`.<br>(default: `ArrayCursor`)
- Change `ArrayCursor::$cursor` accessibility from `protected` to `public`. We can correctly call `json_encode(ArrayCursor)` without requiring any interfaces. 

# Goal

I'd like to support both conventional array-style cursor and serialized-string-style cursor. This proposal makes it possible without a lot of breaking backward compatibilities.

# Example of Implementation

```php
class MyCursor extends ArrayCursor implements JsonSerializable
{
    public static function parse(string $serial): static
    {
        return new static((array)json_decode(base64_decode($serial), true));
    }

    public function jsonSerialize(): string
    {
        return base64_encode(json_encode($this->cursor));
    }
}
```

```php
$cursor = MyCursor::parse([
    'id' => 3,
    'created_at' => '2017-01-10 00:00:00',
    'updated_at' => '2017-01-20 00:00:00',
]);

$query = (new Paginator())
    ->forward()
    ->limit(5)
    ->orderByDesc('updated_at')
    ->orderByDesc('created_at')
    ->orderByDesc('id')
    ->configure($cursor);

$rows = run_your_query_using_PDO($query);

echo json_encode((new ArrayProcessor())->process($query, $rows)); // The cursor will have string format
```

**Comment by mpyw** [comment]
Todo: `Cursor` implementation cannot be determined on pagination start

**Comment by chitoku-k** [comment]
I'm basically for this proposal.  Can you elaborate on what this means?
> `Cursor` implementation class will be the same as the first argument of `Paginator::paginate()`.
(default: `ArrayCursor`)

**Comment by mpyw** [comment]
@chitoku-k That means the output `Cursor` implementation can be guessed from the input one. However, it's impossible when the first argumemt omitted on starting pagination...

So we can't avoid specifying `Cursor` implementation on settings or passing an empty cursor object, such as `new ArrayCursor()`. <del>If we go on the second choice, the new interface method `Cursor::isEmpty()` should be added.</del> <ins>We already have `Cursor::has()`.</ins>

**Comment by chitoku-k** [comment]
@mpyw That makes sense. <del>I prefer configuring `Cursor` implementation so it doesn’t depend on requested parameter. As a design, any implementation should not require the request be in specific format as less as it could.</del>

I changed my mind: passing an empty cursor object looks nicer.

**Comment by chitoku-k** [comment]
If we went on with an empty cursor object, the `parse` would have to return an object which is consistently empty. How about adding a readonly object like `Cursor::$empty`?
