### ISSUE TITLE
incomplete return type docblock for Cursor contract get method

### ISSUE THREAD

**Issue by Ilyes512** [lampager/lampager#39]
Return docblock of contract needs to be `int|string|null` instead?

Partial of `Cursor.php` contract:
```php
    /**
     * Return a cursor specified by the column.
     *
     * @param  string     $column Column.
     * @return int|string
     */
    public function get($column);
```

See https://github.com/lampager/lampager/blob/8642e5066900bf5ebced633c8ce1edaa3367c963/src/Contracts/Cursor.php.

The `ArrayCursor.php` implementation can return null:

```php
    /**
     * {@inheritdoc}
     */
    public function get($column)
    {
        return isset($this->cursor[$column]) ? $this->cursor[$column] : null;
    }
```

See https://github.com/lampager/lampager/blob/8642e5066900bf5ebced633c8ce1edaa3367c963/src/ArrayCursor.php

**Comment by chitoku-k** [comment]
Thanks for reporting! You're right in that `null` is missing from the docblock.
