### ISSUE TITLE
Implement bulk-configure method that receives associative array

### ISSUE THREAD

**Issue by mpyw** [lampager/lampager#4]
# Proposal

Some framework requires associative array instead of method chaining. We should make a new method for convenience.

```php
(new Paginator())->newSettingMethod([
    'orders' => [['created_at', 'asc'], ['id', 'asc']],
    'forward' => true,
    'inclusive' => true,
    'limit' => 10,
])
```

What's the proper name of `newSettingMethod`?

**Comment by mpyw** [comment]
Currently `->configure()` is used for the different purposes. My option is

- `->newSettingMethod()` ➔ `->configure()`
- original `->configure()` ➔ `->query()`

**Comment by chitoku-k** [comment]
`Paginator::fromArray`

**Comment by mpyw** [comment]
Sounds good

**Comment by m3m0r7** [comment]
@chitoku-k too

**Comment by chitoku-k** [comment]
I think the option can either be an array or a class whose members are compatible.

**Comment by mpyw** [comment]
Simple array is the better

**Comment by chitoku-k** [comment]
This issue should depend on #3.
