### ISSUE TITLE
Provide Cursor Interface

### ISSUE THREAD

**Issue by chitoku-k** [lampager/lampager#7]
## Proposal

The current implementation of `Lampager\Query\ConditionGroup::create` only accepts `$cursor` of an associative array; however, this is a lack of flexibility in a situation where cursor needs extension.

For this may also make the method useless, an associative array should thus be kept supported. 

## Example

```php
<?php

namespace Lampager\Query;

interface Cursor
{
    /**
     * @param  string $column
     * @return array
     */
    public function value($column);
}
```

## Usage

```php
<?php

use Lampager\Query\Cursor;

\Lampager\Query\Query::create(
    [],
    new class implements Cursor
    {
        public function value($column)
        {
            return $this->operation->that->can->hardly->be->done($column);
        }
    },
    $limit,
    $backward,
    $exclusive,
    $seekable
);
```

**Comment by chitoku-k** [comment]
How do you think it should ensure the existence of the value?

Thinking this kinda method...

```php
interface Cursor
{
    /**
     * @param  string $column
     * @return bool
     */
    public function has($column);

    /**
     * @param  string $column
     * @return array
     */
    public function get($column);
}
```

**Comment by mpyw** [comment]
Another option:

```php
<?php

namespace Lampager\Query;

abstract class Cursor implements \JsonSerializable
{
    /**
     * @param string $column
     * @return int|string
     */
    abstract public function field($column);

    /**
     * @return mixed
     */
    abstract public function jsonSerialize();
}
```

**Comment by chitoku-k** [comment]
Why should it require `jsonSerialize`?

**Comment by chitoku-k** [comment]
I am creating an ArrayCursor that implements `Cursor` in order to have a consistency with `array`-based parameter. What do you think?

**Comment by mpyw** [comment]
I agree with accepting both `array` and `ArrayCursor`. (It's just like auto-boxing)

Accepting only `ArrayCursor` will achieve strict and consistent interface, however, it will lose convenience instead.

**Comment by mpyw** [comment]
My belief is:

- Internal should be strictly typed
- Interface should be as flexible as possible

**Comment by chitoku-k** [comment]
Seems to be the same concept.

What is your intention about making `toArray` stuff?
